### ISSUE TITLE
Embedding Custom HTML in gt Tables blog page is blank

### ISSUE THREAD

**Issue by mfiorina** [jthomasmock/radix_themockup#4]
Hello,

I have been learning a lot from your blog post on how to use kableExtra in gt tables, but today I tried to open it after not having looked at it for a few weeks and unfortunately the page is blank... This seems to only happen for this post, the others work fine for me. Is this something that can be fixed?

See screenshot [here](https://snipboard.io/aEwHuR.jpg). Thank you,

Best,

Marc-Andrea Fiorina

**Comment by jthomasmock** [comment]
Hey @mfiorina ! Thanks for letting me know, I had to redo a few posts while trying to shrink some file sizes. It's back up and live.
